// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSrhhslai12ZLKHnV2qt7MNh1juikp8hw',
    appId: '1:1063012352866:web:cf99bf5a0c87867e9a623b',
    messagingSenderId: '1063012352866',
    projectId: 'volkan-589c1',
    authDomain: 'volkan-589c1.firebaseapp.com',
    storageBucket: 'volkan-589c1.firebasestorage.app',
    measurementId: 'G-9Q1DR1ZNCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYB6z0ZJI9ttgidzE_NumNXmvc6pXsneU',
    appId: '1:1063012352866:android:e0168a5fc3ac7df99a623b',
    messagingSenderId: '1063012352866',
    projectId: 'volkan-589c1',
    storageBucket: 'volkan-589c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_yg5CwhitrP5M1x1lWrjXAgDE-r7948',
    appId: '1:1063012352866:ios:27ee353f95df690c9a623b',
    messagingSenderId: '1063012352866',
    projectId: 'volkan-589c1',
    storageBucket: 'volkan-589c1.firebasestorage.app',
    iosBundleId: 'com.example.gozenBoardingPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf_yg5CwhitrP5M1x1lWrjXAgDE-r7948',
    appId: '1:1063012352866:ios:27ee353f95df690c9a623b',
    messagingSenderId: '1063012352866',
    projectId: 'volkan-589c1',
    storageBucket: 'volkan-589c1.firebasestorage.app',
    iosBundleId: 'com.example.gozenBoardingPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSrhhslai12ZLKHnV2qt7MNh1juikp8hw',
    appId: '1:1063012352866:web:7daca6a7e873f4d09a623b',
    messagingSenderId: '1063012352866',
    projectId: 'volkan-589c1',
    authDomain: 'volkan-589c1.firebaseapp.com',
    storageBucket: 'volkan-589c1.firebasestorage.app',
    measurementId: 'G-84GK2BPW6M',
  );
}
